CREATE TYPE "Domain" AS ENUM ('LAB', 'SECURITY', 'CAREER', 'GAMES', 'FAMILY', 'SYSTEM');
CREATE TYPE "Severity" AS ENUM ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE "AttentionStatus" AS ENUM ('NEW', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED');
CREATE TYPE "IntegrationState" AS ENUM ('UNKNOWN', 'HEALTHY', 'DEGRADED', 'DOWN', 'DISABLED');

CREATE TABLE "UserSettings" ("id" TEXT NOT NULL, "timezone" TEXT NOT NULL DEFAULT 'America/New_York', "theme" TEXT NOT NULL DEFAULT 'homebase-dark', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "UserSettings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Integration" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "name" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT false, "mockMode" BOOLEAN NOT NULL DEFAULT true, "config" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Integration_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IntegrationHealth" ("id" TEXT NOT NULL, "integrationId" TEXT NOT NULL, "state" "IntegrationState" NOT NULL DEFAULT 'UNKNOWN', "lastAttemptAt" TIMESTAMP(3), "lastSuccessAt" TIMESTAMP(3), "lastError" TEXT, "latencyMs" INTEGER, "consecutiveErrors" INTEGER NOT NULL DEFAULT 0, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "IntegrationHealth_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Asset" ("id" TEXT NOT NULL, "externalId" TEXT, "name" TEXT NOT NULL, "kind" TEXT NOT NULL, "domain" "Domain" NOT NULL DEFAULT 'LAB', "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Asset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Service" ("id" TEXT NOT NULL, "assetId" TEXT, "name" TEXT NOT NULL, "kind" TEXT NOT NULL, "state" TEXT NOT NULL, "version" TEXT, "source" TEXT NOT NULL, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "metadata" JSONB, CONSTRAINT "Service_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MetricSnapshot" ("id" BIGSERIAL NOT NULL, "assetId" TEXT, "serviceId" TEXT, "metric" TEXT NOT NULL, "value" DOUBLE PRECISION NOT NULL, "unit" TEXT, "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MetricSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AttentionItem" ("id" TEXT NOT NULL, "fingerprint" TEXT NOT NULL, "domain" "Domain" NOT NULL, "title" TEXT NOT NULL, "summary" TEXT NOT NULL, "severity" "Severity" NOT NULL, "urgency" INTEGER NOT NULL, "relevance" INTEGER NOT NULL, "consequence" INTEGER NOT NULL, "recency" INTEGER NOT NULL, "confidence" INTEGER NOT NULL, "score" DOUBLE PRECISION NOT NULL, "explanation" TEXT NOT NULL, "source" TEXT NOT NULL, "sourceUrl" TEXT, "entity" TEXT NOT NULL, "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "status" "AttentionStatus" NOT NULL DEFAULT 'NEW', "action" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AttentionItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Goal" ("id" TEXT NOT NULL, "domain" "Domain" NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Goal_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GoalProgress" ("id" TEXT NOT NULL, "goalId" TEXT NOT NULL, "value" INTEGER NOT NULL, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "GoalProgress_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CalendarEvent" ("id" TEXT NOT NULL, "externalId" TEXT, "calendar" TEXT NOT NULL, "title" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3), "allDay" BOOLEAN NOT NULL DEFAULT false, "location" TEXT, "source" TEXT NOT NULL, "metadata" JSONB, CONSTRAINT "CalendarEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JobPosting" ("id" TEXT NOT NULL, "externalId" TEXT, "title" TEXT NOT NULL, "company" TEXT NOT NULL, "location" TEXT, "arrangement" TEXT, "salaryMin" INTEGER, "salaryMax" INTEGER, "source" TEXT NOT NULL, "sourceUrl" TEXT, "postedAt" TIMESTAMP(3), "summary" TEXT, "matchScore" INTEGER, "careerValueScore" INTEGER, "reasons" JSONB, "gaps" JSONB, "status" TEXT NOT NULL DEFAULT 'NEW', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "JobPosting_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JobSkill" ("id" TEXT NOT NULL, "jobPostingId" TEXT NOT NULL, "name" TEXT NOT NULL, "required" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "JobSkill_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SecurityAdvisory" ("id" TEXT NOT NULL, "externalId" TEXT NOT NULL, "source" TEXT NOT NULL, "title" TEXT NOT NULL, "summary" TEXT, "severity" "Severity" NOT NULL, "publishedAt" TIMESTAMP(3), "modifiedAt" TIMESTAMP(3), "sourceUrl" TEXT, "knownExploited" BOOLEAN NOT NULL DEFAULT false, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SecurityAdvisory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TechnologyInventory" ("id" TEXT NOT NULL, "assetId" TEXT, "product" TEXT NOT NULL, "vendor" TEXT, "version" TEXT, "source" TEXT NOT NULL, "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TechnologyInventory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Game" ("id" TEXT NOT NULL, "slug" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Game_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TrackedGameEntity" ("id" TEXT NOT NULL, "gameId" TEXT NOT NULL, "externalId" TEXT, "name" TEXT NOT NULL, "kind" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "TrackedGameEntity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GameUpdate" ("id" TEXT NOT NULL, "gameId" TEXT NOT NULL, "externalId" TEXT, "title" TEXT NOT NULL, "summary" TEXT, "publishedAt" TIMESTAMP(3), "source" TEXT NOT NULL, "sourceUrl" TEXT, "metadata" JSONB, CONSTRAINT "GameUpdate_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FeedSource" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "name" TEXT NOT NULL, "domain" "Domain" NOT NULL, "url" TEXT, "enabled" BOOLEAN NOT NULL DEFAULT false, "refreshMinutes" INTEGER NOT NULL DEFAULT 60, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "FeedSource_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FeedItem" ("id" TEXT NOT NULL, "feedSourceId" TEXT NOT NULL, "externalId" TEXT, "title" TEXT NOT NULL, "summary" TEXT, "publishedAt" TIMESTAMP(3), "sourceUrl" TEXT, "payload" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FeedItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CollectorRun" ("id" TEXT NOT NULL, "integrationId" TEXT NOT NULL, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "success" BOOLEAN, "itemCount" INTEGER NOT NULL DEFAULT 0, "error" TEXT, "metadata" JSONB, CONSTRAINT "CollectorRun_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Integration_key_key" ON "Integration"("key");
CREATE UNIQUE INDEX "IntegrationHealth_integrationId_key" ON "IntegrationHealth"("integrationId");
CREATE UNIQUE INDEX "Asset_kind_externalId_key" ON "Asset"("kind", "externalId");
CREATE INDEX "MetricSnapshot_metric_capturedAt_idx" ON "MetricSnapshot"("metric", "capturedAt");
CREATE UNIQUE INDEX "AttentionItem_fingerprint_key" ON "AttentionItem"("fingerprint");
CREATE INDEX "AttentionItem_status_score_idx" ON "AttentionItem"("status", "score");
CREATE INDEX "AttentionItem_domain_lastSeenAt_idx" ON "AttentionItem"("domain", "lastSeenAt");
CREATE INDEX "CalendarEvent_startsAt_idx" ON "CalendarEvent"("startsAt");
CREATE UNIQUE INDEX "CalendarEvent_source_externalId_key" ON "CalendarEvent"("source", "externalId");
CREATE INDEX "JobPosting_status_matchScore_idx" ON "JobPosting"("status", "matchScore");
CREATE UNIQUE INDEX "JobPosting_source_externalId_key" ON "JobPosting"("source", "externalId");
CREATE UNIQUE INDEX "JobSkill_jobPostingId_name_key" ON "JobSkill"("jobPostingId", "name");
CREATE UNIQUE INDEX "SecurityAdvisory_source_externalId_key" ON "SecurityAdvisory"("source", "externalId");
CREATE INDEX "TechnologyInventory_product_version_idx" ON "TechnologyInventory"("product", "version");
CREATE UNIQUE INDEX "Game_slug_key" ON "Game"("slug");
CREATE UNIQUE INDEX "TrackedGameEntity_gameId_kind_name_key" ON "TrackedGameEntity"("gameId", "kind", "name");
CREATE UNIQUE INDEX "GameUpdate_source_externalId_key" ON "GameUpdate"("source", "externalId");
CREATE UNIQUE INDEX "FeedSource_key_key" ON "FeedSource"("key");
CREATE UNIQUE INDEX "FeedItem_feedSourceId_externalId_key" ON "FeedItem"("feedSourceId", "externalId");
CREATE INDEX "CollectorRun_integrationId_startedAt_idx" ON "CollectorRun"("integrationId", "startedAt");

ALTER TABLE "IntegrationHealth" ADD CONSTRAINT "IntegrationHealth_integrationId_fkey" FOREIGN KEY ("integrationId") REFERENCES "Integration"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Service" ADD CONSTRAINT "Service_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MetricSnapshot" ADD CONSTRAINT "MetricSnapshot_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MetricSnapshot" ADD CONSTRAINT "MetricSnapshot_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GoalProgress" ADD CONSTRAINT "GoalProgress_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JobSkill" ADD CONSTRAINT "JobSkill_jobPostingId_fkey" FOREIGN KEY ("jobPostingId") REFERENCES "JobPosting"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TechnologyInventory" ADD CONSTRAINT "TechnologyInventory_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TrackedGameEntity" ADD CONSTRAINT "TrackedGameEntity_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GameUpdate" ADD CONSTRAINT "GameUpdate_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FeedItem" ADD CONSTRAINT "FeedItem_feedSourceId_fkey" FOREIGN KEY ("feedSourceId") REFERENCES "FeedSource"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CollectorRun" ADD CONSTRAINT "CollectorRun_integrationId_fkey" FOREIGN KEY ("integrationId") REFERENCES "Integration"("id") ON DELETE CASCADE ON UPDATE CASCADE;
